INSERT INTO CompanyRemarks (RemarkPattern, CompanyName) VALUES
('%HDFCAMC%', 'HDFC Asset Management Co Ltd'),
('%Ashok Leyland%', 'Ashok Leyland'),
('%HDFC LIMITED%', 'HDFC Bank Limited'),
('%HDFCLTD%', 'HDFC Bank Limited'),
('%INFOSYS%', 'Infosys Limited'),
('%ICICI%', 'ICICI Bank Limited'),
('%Muthoot%', 'Muthoot Finance'),
('%HINDUSTAN%', 'Hindustan Unilever Limited'),
('%Astral%', 'Astral Pipes'),
('%RELIANCE%', 'Reliance Industries Ltd'),
('%HDFCBANK%', 'HDFC Bank Ltd'),
('%Meghmani%', 'Meghmani Organics'),
('%Bajaj Finance%', 'Bajaj Finance Limited'),
('%MOTHERSON%', 'Motherson Sumi'),
('%HAPPIEST%', 'Happiest Minds Limited'),
('%EXIDE%', 'Exide Industries'),
('%SAMVARDHANA%', 'Motherson Sumi'),
('%Indian Railway%', 'IRCTC Limited'),
('%Deepak%', 'Deepak Fertilizers'),
('%JAMNA%', 'Jamna Auto Industries'),
('%HDFC Life%', 'HDFC Life Insurance'),
('%HDFCLIFE%', 'HDFC Life Insurance'),
('%PIDILITE%', 'Pidilite Industries'),
('%COSMO%', 'Cosmo Films'),
('%LTIMind%', 'LTI Mindtree'),
('%AARTI%', 'Aarti Industries'),
('%Relaxo%', 'Relaxo Footwears'),
('%Prince%', 'Prince Pipes'),
('%LNTINFO%', 'LTI Mindtree'),
('%Force%', 'Force Motors Limited'),
('%Godrej%', 'Godrej Industries'),
('%SRF%', 'SRF Limited'),
('%Varun%', 'Varun Beverages Limited'),
('%TCS%', 'Tata Consultancy Services'),
('%HDFC Asset%', 'HDFC Asset Management Co Ltd'),
('%NILA%', 'NILA Infrastructure'),
('%Wipro%', 'Wipro Limited'),
('%Supriya%', 'Supriya Lifescience Ltd'),
('%SBICARD%', 'SBI Cards Limited'),
('%Prakash%', 'Prakash Industries Limited'),
('%Bandhan%', 'Bandhan Bank'),
('%Larsen%', 'LTI Mindtree'),
('%UNO%', 'UNO Minda Limited'),
('%KNR%', 'KNR Construction'),
('%Trident%', 'Trident Limited'),
('%GMM%', 'GMM Pfaudler'),
('%NAVIN%', 'Navin Fluorine International Limited'),
('%Bajaj Finserv%', 'Bajaj Finserv Limited'),
('%AartiPhar%', 'Aarti Pharmacy'),
('%EASY%', 'Ease My Trip'),
('%Talbros%', 'Talbros Automotive'),
('%DFM%', 'DFM Foods Limited'),
('%TITAN%', 'Titan Company Ltd'),
('%Asahi%', 'Asahi India Glass Ltd'),
('%Minda%', 'UNO Minda Limited'),
('%MARKSANS%', 'Marksans Pharma'),
('%HDFC DIV%', 'HDFC Bank Limited'),
('%HDFC Bank%', 'HDFC Bank Limited'),
('%TATA CONSULTANCE%', 'Tata Consultancy Services'),
('%SBI Cards%', 'SBI Cards Limited'),
('%MIN1S%', 'Uncategorized Company'),
('%NFIL%', 'Navin Fluorine International Limited'),
('%HDFC AMCL%', 'HDFC Asset Management Co Ltd'),
('ACH/AIL%', 'Uncategorized Company'),
('ACH/FMLFNL%', 'Uncategorized Company'),
('%RBL Bank Limited%', 'RBL Bank Limited')