INSERT INTO ExclusionPatterns (ExclusionPattern) VALUES
('%HARSH%'),
('%ATM/WDL%'),
('%E00031%'),
('%FLIPKART%'),
('%WESTERN%'),
('%SUNEETA%'),
('%INT.PD%'),
('%INCOME%'),
('%MMT%'),
('%REFUND%'),
('%GOA%'),
('%FIDELITY%'),
('%SHAADI%'),
('%BSNL%'),
('%BIL%'),
('%UPI%'),
('%BOOKMYSHOW%'),
('%CASH%'),
('%NEFT%'),
('%GOOGLE%'),
('REF KARAN FILLING AND%'),
('%UBER%'),
('REV OF TXN%'),
('VPS%'),
('%RVSL%'),
('REV%'),
('%SUNBELT%'),
('%DIGITUP%'),
('%KHAN%'),
('%IMPS%'),
('%DNRPS6094B%'),
('CMS/ CMS581741169'),
('CMS/ CMS603406948'),
('%IRCTC%'),
('%CHRG%'),
('%GST ADJ%'),
('%BHIM%');
